{% set name = "sqlite_zstd_vfs" %}
{% set version = "0.0.2024.01.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mlin/sqlite_zstd_vfs/archive/228f6d12c55f69e584d909024d8ef9d599f2f398.tar.gz
  sha256: a43a8c939d150a7e37ef9f0a4cf93cdf0c554d6de025ef25677e973c95b79db0
  patches:
    - update.diff


build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
    - sed
  host:
    - sqlite
    - zstd
    - libcurl
  run:
    - sqlite

test:
  commands:
    - echo '.quit' | sqlite3 -cmd ".load zstd_vfs"

about:
  home: https://github.com/mlin/sqlite_zstd_vfs
  summary: 'SQLite3 extension for read/write storage compression with Zstandard'
  description: |
    This SQLite VFS extension provides streaming storage compression with
    Zstandard, transparently compressing pages of the main database file as
    they're written out, and later decompressing them as they're read in. It
    runs page de/compression on background threads and occasionally generates
    dictionaries to improve subsequent compression.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - matthiasdiener
